acesso_spy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from acessos import urls as acessos_urls
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', include(acessos_urls)),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name="logout"),
    path('admin_spy/', admin.site.urls),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acessos/urls.py
from django.urls import path
from acessos.views import lista_acessos, novo_acesso, alterar_acesso, desativar_acesso
from .views import home, esqueci_senha, acessar, ativar_acesso, login_view, logout_view


urlpatterns = [
    path('lista/', lista_acessos, name="lista"),
    path('novo/', novo_acesso, name="novo"),
    path('alterar/<int:id>/', alterar_acesso, name="alterar"),
    path('desativar/<int:id>/', desativar_acesso, name="desativar"),
    path('ativar/<int:id>/', ativar_acesso, name="ativar"),
    path('esqueceu_senha/', esqueci_senha, name="esqueci"),
    path('', login_view , name="login"),
    path('logout/', logout_view , name="logout"),
    path('acesso/', acessar, name="acessar"),
]

acessos/models.py
from django.db import models

class cadastro_acesso(models.Model):
    cpf = models.CharField(max_length=11, unique=True, help_text="Por favor insira um CPF válido, somente números.")
    nome = models.CharField(max_length=30)
    senha = models.CharField(max_length=8)
    celular = models.CharField(max_length=11, help_text="Por favor insira somente números. Ex.51999999999")
    email = models.EmailField()
    obs = models.TextField(max_length=150, null=True, blank=True)
    data_ini = models.DateTimeField ( auto_now = False , auto_now_add = False)
    data_fim = models.DateTimeField ( auto_now = False , auto_now_add = False)
    ativo = models.BooleanField(default=True)
    foto = models.ImageField(upload_to='fotos_cadastros', null=True, blank=True)


    def __str__(self):
        return self.nome + ' - CPF: ' + self.cpf + ' - Senha: ' + self.senha + ' - Celular: ' + self.celular 

class config_geral(models.Model):
    nome_empresa = models.CharField(max_length=30, null=True, blank=True)
    cor_login = models.CharField(max_length=10, null=True, blank=True)
    cor_main = models.CharField(max_length=10, null=True, blank=True)
    cor_menu = models.CharField(max_length=10, null=True, blank=True)
    obs = models.TextField(max_length=150, null=True, blank=True)
    foto_bg = models.ImageField(upload_to='fotos_cadastros', null=True, blank=True)
    foto_logo = models.ImageField(upload_to='fotos_cadastros', null=True, blank=True)


    def __str__(self):
        return self.nome_empresa


class config_comunicacao(models.Model):
    user = models.CharField(max_length=50, null=True, blank=True)
    senha = models.CharField(max_length=50, null=True, blank=True)
    email = models.EmailField()
    email_copia = models.EmailField()
    porta = models.IntegerField
    smtp = models.CharField(max_length=50, null=True, blank=True)
    autenticacao = models.BooleanField(default=True)
    ssl = models.BooleanField(default=True)
    obs = models.TextField(max_length=150, null=True, blank=True)


    def __str__(self):
        return self.user 

acessos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from .models import cadastro_acesso, config_geral, config_comunicacao
from .form import AcessoForm, RecuperarSenha, AcessoForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from .utils import *
import requests


@login_required
def lista_acessos(request):
    if membro_da_equipe(request.user):
        acessos = cadastro_acesso.objects.order_by('ativo')
        #geral = config_geral.objects.get(pk=1)
        #cor_menu = '<nav id="menus" style="background-color:' + (geral.cor_menu) + ';" >'
        geral = ''
        cor_menu = ''

        busca = request.GET.get('search')
        if busca:
            if isnumber(busca):
                acessos = cadastro_acesso.objects.filter(cpf__icontains = busca)
            else:
                acessos = cadastro_acesso.objects.filter(nome__icontains = busca)

        return render(request, 'list.html', {'acessos': acessos, 'geral': geral, 'cor_menu': cor_menu})

    return redirect('acessar')


@login_required
def novo_acesso(request):
    if membro_da_equipe(request.user):
        form = AcessoForm(request.POST or None, request.FILES or None)
        #geral = config_geral.objects.get(pk=1)
        #cor_menu = '<nav id="menus" style="background-color:' + (geral.cor_menu) + ';" >'
        geral = ''
        cor_menu = ''

        if form.is_valid():
            #print(form['cpf'].data)
            user = User.objects.create_user((form['cpf'].data), (form['email'].data), (form['senha'].data))
            user.last_name = 'usuariocomum'
            user.first_name = form['nome'].data
            user.save()
            form.save()

            return redirect('lista')
        return render(request, 'acesso_form.html', {'form': form, 'geral': geral, 'cor_menu': cor_menu})

    return redirect('acessar')


@login_required
def alterar_acesso(request, id):
    if membro_da_equipe(request.user):
        cadastro = get_object_or_404(cadastro_acesso, pk=id)
        form = AcessoForm(request.POST or None, request.FILES or None, instance=cadastro)
        #geral = config_geral.objects.get(pk=1)
        #cor_menu = '<nav id="menus" style="background-color:' + (geral.cor_menu) + ';" >'
        geral = ''
        cor_menu = ''

        username = cadastro.cpf

        if form.is_valid():
            user = User.objects.get(username=username)
            user.first_name = form['nome'].data
            user.username = form['cpf'].data
            user.set_password(form['senha'].data)
            user.save()
            #print (form['nome'].data)
            form.save()
            return redirect('lista')

        return render(request, 'acesso_form.html', {'form': form, 'cadastro': cadastro, 'cor_menu': cor_menu})
    
    return redirect('acessar')


@login_required
def desativar_acesso(request, id):
    if membro_da_equipe(request.user):
        cadastro = get_object_or_404(cadastro_acesso, pk=id)
        action = 'desativar'
        #geral = config_geral.objects.get(pk=1)
        #cor_menu = '<nav id="menus" style="background-color:' + (geral.cor_menu) + ';" >'
        geral = ''
        cor_menu = ''

        if request.method == 'POST':
            cadastro.ativo = False
            cadastro.save()
            return redirect('lista')

        return render(request, 'acesso_desativar.html', {'cadastro': cadastro, 'action': action, 'geral': geral, 'cor_menu': cor_menu})

    return redirect('acessar')


@login_required
def ativar_acesso(request, id):
    if membro_da_equipe(request.user):
        cadastro = get_object_or_404(cadastro_acesso, pk=id)
        action = 'ativar'
        #geral = config_geral.objects.get(pk=1)
        #cor_menu = '<nav id="menus" style="background-color:' + (geral.cor_menu) + ';" >'
        geral = ''
        cor_menu = ''

        if request.method == 'POST':
            cadastro.ativo = True
            cadastro.save()
            return redirect('lista')

        return render(request, 'acesso_desativar.html', {'cadastro': cadastro, 'action': action, 'geral': geral, 'cor_menu': cor_menu})

    return redirect('acessar')


def esqueci_senha(request):
    form = RecuperarSenha(request.POST or None, request.FILES or None)
    #geral = config_geral.objects.get(pk=1)
    #cor_menu = '<nav id="menus" style="background-color:' + (geral.cor_menu) + ';" >'
    geral = ''
    cor_menu = ''

    if request.method == 'POST':
        print(form['cpf'].data)
        cadastro = cadastro_acesso.objects.get(cpf=form['cpf'].data)
        print(cadastro.nome)
        print(cadastro.celular)
        print(cadastro.email)
        return redirect('login')

    return render(request, 'esqueci_senha.html', {'form': form, 'geral': geral, 'cor_menu': cor_menu})
    

def home(request):
    geral = config_geral.objects.get(pk=1)

    return redirect('login', {'geral': geral})


@login_required
def acessar(request):
    #geral = config_geral.objects.get(pk=1)
    #cor_menu = '<nav id="menus" style="background-color:' + (geral.cor_menu) + ';" >'
    geral = ''
    cor_menu = ''


    #url = "http://tisul.no-ip.info:8989/login"
    #content = "{\"cpf\": \"90916743004\",\"senha\": \"1234\"}"
    #headers = {
    #    'user-agent': "vscode-restclient",
    #    'content-type': "application/json"
    #    }
    #try:
    #    response = requests.request("GET", url, data=content, headers=headers)

    #    data = response.json()
    #except:
    #    data = ""
    data = ""

    acessos = get_object_or_404(cadastro_acesso, cpf=request.user)
        
    return render(request, 'qr_code.html', {'acessos': acessos, 'data': data, 'geral': geral, 'cor_menu': cor_menu})


def login_view(request):
    nome = request.POST.get('username')
    senha = request.POST.get('password')
    user = authenticate(request, username=nome, password=senha)

    ########
    #geral = config_geral.objects.order_by('id')
    #if geral:
    #    action = 'Seja Bem Vindo a ' + (geral.nome_empresa)
    #else:
    action = 'Seja Bem Vindo a sua empresa'
    #cor_login = '<div class="login-spy" style="background-color:' + (geral.cor_login) + ';" >'
    #cor_menu = '<nav id="menus" style="background-color:' + (geral.cor_menu) + ';" >'
    cor_login = ''
    cor_menu = ''

    if user is not None:
        login(request, user)
        
        if membro_da_equipe(request.user):
            acessos = cadastro_acesso.objects.order_by('ativo')
            

            return render(request, 'list.html', {'acessos': acessos, 'cor_menu': cor_menu})

        return redirect('acessar')
    else:
        return render(request, 'login_logout.html', {'action': action, 'cor_login': cor_login})


def logout_view(request):
    logout(request)
    
    #cor_login = '<div class="login-spy" style="background-color:' + (geral.cor_login) + ';" >'
    #cor_menu = '<nav id="menus" style="background-color:' + (geral.cor_menu) + ';" >'
    cor_login = ''
    cor_menu = ''

    action = 'Sua empresa' + '<br>' +'Agradece pela Visita!'
    
    return render(request, 'login_logout.html', {'action': action, 'cor_login': cor_login})

acessos/templates/acesso_desativar.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ action }} {% endblock %}

{% block main %}
    <div class="branco">
        <h1 id="certeza-texto" class="text-center">Tem certeza que deseja {{ action }} o cadastro de {{ cadastro.nome }}?</h1>    
        
        <form class="text-center" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Sim, tenho certeza.</button>
            <a href="{% url 'lista' %}"><button id="nao" type="button" class="btn btn-info"> Não, me tire daqui.</button></a>
        </form>
        
    </div>

{% endblock %}

acessos/templates/acesso_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %}
{% if cadastro %}
{{ cadastro.nome }}
{% else %}
Novo Acesso
{% endif %}
{% endblock %}

{% block main %}
<div class="branco" >       
    <form id="acesso-form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div  class="form-row">
            <div class="form-group col-md-6">    
                <label class="control-label" for="id_nome">Nome</label>
                <div class=" ">
                    <input type="text" name="nome" maxlength="30" class="form-control" required="" id="id_nome" value="{{ cadastro.nome }}">
                </div>
            </div>

            <div class="form-group col-md-6">  
                <label class="control-label" for="id_celular">Celular</label>
                <div class=" ">
                    <input type="text" name="celular" maxlength="14" minlength="10" class=" form-control" required="" id="id_celular" value="{{ cadastro.celular }}">
                </div>
            </div>
        </div>

       
        <div class="form-row">
            <div class="form-group col-md-6">
                <label class="control-label  " for="id_cpf">Cpf</label>
                <div class=" ">
                    <input type="text" name="cpf" minlength="11" class=" form-control" required="" id="id_cpf" value="{{ cadastro.cpf }}"> 
                </div>
            </div>
            <div class="form-group col-md-6">  
                <label class="control-label  " for="id_senha">Senha</label>
                <div class=" ">
                    <input type="text" name="senha" maxlength="4" minlength="4" class=" form-control" required="" id="id_senha" value="{{ cadastro.senha }}">
                </div>
            </div>
        </div>
        

        <div class="form-group">    
            <label class="control-label  " for="id_email">Email</label>
            <div class=" ">
                <input type="email" name="email" maxlength="254" class=" form-control" required="" id="id_email" value="{{ cadastro.email }}">
            </div>
        </div>


        <div class="form-row">
            <div class="form-group col-md-6">
                <label class="control-label  " for="id_data_ini">Data inicial</label>
                <div class=" ">
                    <input type="datetime-local" name="data_ini" class="form-control" required="" id="id_data_ini" value="{{ cadastro.data_ini|date:"Y-m-d" }}T{{ cadastro.data_ini|time:"H:i" }}">  
                </div>
            </div>
            <div class="form-group col-md-6">    
                <label class="control-label  " for="id_data_fim">Data final</label>
                <div class=" ">
                    <input type="datetime-local" name="data_fim" class="form-control" required="" id="id_data_fim" value="{{ cadastro.data_fim|date:"Y-m-d" }}T{{ cadastro.data_fim|time:"H:i" }}">
                </div>  
            </div>
        </div>


        <div class="form-group">  
            <label class="control-label  " for="id_foto">Foto</label>
            <div class=" ">
                {% if cadastro %}
                <p class="file-upload">Atualmente: <a href="/media/{{ cadastro.foto }}">{{ cadastro.foto }}</a><br>
                Modificar:
                {% endif %}
                <input type="file" name="foto" accept="image/*" id="id_foto" value="">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label  " for="id_obs">Obs</label>
            <div class=" ">
                <textarea name="obs" cols="40" rows="10" maxlength="150" class=" form-control" id="id_obs" value="{{ cadastro.obs }}"></textarea>  
            </div>
        </div>

        <button class="btn btn-success" type="submit">Salvar</button>
    </form>
</div>
    

{% endblock %}

acessos/templates/base.html
{% load static %}
{% load bootstrap %}

<!DOCTYPE HTML>
<html lang="pt-br">
<head>
  <title>{% block title %} {% endblock %}</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  <meta name="author" content="Cristian Raach">
</head>
<body>
    <div class="container">
        {% if cor_menu %} 
          {{ cor_menu|safe }}
        {% else %}
          <nav id="menus">
        {% endif %}
  
          {% if user.is_authenticated %}
                <div id="tisul" class="form-row">
                  <div class="col-6">
                    <h1>Acesso fácil</h1><a id="a-no-decoration"  onclick="window.open('http://www.raach.com.br/');" href="#"><p> by Cristian Raach</p></a>
                    
                      {% if user.first_name %}
                        <h6 class="h6-login oi">Olá {{ user.first_name }}</h6>
                      {% else %}
                        <h6 class="h6-login oi">Olá {{ user.username }}</h6>
                      {% endif %}
                    
                  </div>
                  <div class="col-6" style="text-align: right">
                      <p>Your logo here.</p>
                  </div>
                </div>

                <div class="text-center" id="menus-botoes">
                    
                  {% if user.is_staff %}

                      <a href="{% url 'novo' %}" id="a-no-decoration">
                        <button type="button" class="btn btn-success"><i class="fas fa-user-plus"></i> Novo Acesso</button>
                      </a>

                      <a href="{% url 'lista' %}" id="a-no-decoration">
                        <button class="btn btn-secondary">Lista</button>
                      </a>

                    {% endif %}

                    <!--<a href="{% url 'login' %}" id="a-no-decoration">
                      <button class="btn btn-secondary">Inicio</button>
                    </a>-->

                    <a href="{% url 'logout' %}" id="a-no-decoration">
                      <button class="btn btn-secondary">Sair</button>
                    </a>
                        
                </div>

          {% endif %}

        </nav>
        
      {% block main %}
      {% endblock %}
  
    </div>


  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/qrcode.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
   
  </body>
</html>

acessos/templates/esqueci_senha.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Esqueci a senha {% endblock %}

{% block main %}
    <div class="branco">
        <h1>Esqueci a senha</h1>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group col-md-6">
                <label class="control-label  " for="id_cpf">Cpf</label>
                <div class=" ">
                    <input type="text" name="cpf" minlength="11" class=" form-control" required="" id="id_cpf"> 
                </div>
            </div>
            <button type="submit">Enviar</button>
        </form>
    </div>

{% endblock %}

acessos/templates/list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}

{% block title %} Lista de Acessos {% endblock %}

{% block main %}
    <section  class="branco-body">
        <form method="GET">
            {% csrf_token %}
            <p class="control-label">Campo de pesquisa</p>
            <div class="form-row div-center">
                
                <div class="form-group col-md-10">    
                    <input type="text" class="form-control" placeholder="Insira um nome ou CPF para buscar." name="search" id="search">
                </div>
                <div class="form-group col-md-2">  
                    <button id="buscar-button" class="btn" type="submit">Buscar</button>
                </div>
            </div>
        </form>

        <ul class="list-group">
            {% for acesso in acessos %}
                <li id="item-lista" class="list-group-item">

                        <a href="{% url 'alterar' acesso.id %}" id="a-no-decoration">
                            <button id="item-lista-nome" type="button" class="btn btn-primary col-md-5">
                                {{ acesso.nome }}
                                {% if acesso.ativo %}
                                    <span class="badge badge-pill badge-secondary" style="background-color: #28a745;">Ativo</span>
                                {% else %}
                                    <span class="badge badge-pill badge-secondary" style="background-color:#dc3545;">Desativado</span>
                                {% endif %}
                                <span id="item-lista-badge" class="badge badge-light">CPF: {{ acesso.cpf }}</span>
                            </button>
                        </a>
                        
                        {% if acesso.ativo %}                    
                            <a href="{% url 'desativar' acesso.id %}" id="a-no-decoration">
                                <button id="item-lista-botoes" class="btn btn-danger col-md-2" title='Bloquear acesso do usuário {{acesso.nome}}'>Bloquear</button>
                            </a>
                        {% else %}
                            <a href="{% url 'ativar' acesso.id %}" id="a-no-decoration">
                                <button id="item-lista-botoes" class="btn btn-info col-md-2" title='Desbloquear acesso do usuário {{acesso.nome}}'>Desbloquear</button>
                            </a>
                        {% endif %}

                        <a  data-action='share/whatsapp/share' onclick="window.open('https://api.whatsapp.com/send?text=Olá {{ acesso.nome }}, para acessar digite no login seu CPF:{{ acesso.cpf }} e Senha:{{ acesso.senha }}. http://raach.com.br/');" href='#' title='Compartilhar no WhatsApp acesso do usuário {{acesso.nome}}'>
                            <button id="item-lista-botoes" class="btn btn-info col-md-2">
                                Email
                            </button>
                        </a>

                    
                        <a  data-action='share/whatsapp/share' onclick="window.open('https://api.whatsapp.com/send?text=Olá {{ acesso.nome }}, para acessar digite no login seu CPF:{{ acesso.cpf }} e Senha:{{ acesso.senha }}. http://raach.com.br/');" href='#' title='Compartilhar no WhatsApp acesso do usuário {{acesso.nome}}'>
                            <button id="item-lista-botoes" class="btn btn-success col-md-2">
                                WhatsApp
                            </button>
                        </a>
                    

                </li>
            {% endfor %}
        </ul> 
    </section>

{% endblock %}

acessos/templates/login_logout.html
{% load static %}
{% load bootstrap %}

<!DOCTYPE HTML>
<html lang="pt-br">
<head>
  <title>{% block title %} {% endblock %}</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  <meta name="author" content="Cristian Raach">
</head>
<body class="is-preload">


<div class="container">  

    {% if form.errors %}
    <p>Seu nome de usuário e senha não coincidem. Por favor, tente novamente.</p>
    {% endif %}

    {% if cor_login %} 
        {{ cor_login|safe }}
    {% else %}
        <div class="login-spy">
    {% endif %}
        <div class="form-login">
            <h2 class="text-center h2-home">{{ action|safe }}</h2>                      
            
            {% if user.is_authenticated %}
                {% if user.first_name %}
                    <h6 class="text-center h6-login oi">Olá {{ user.first_name }}</h6>
                {% else %}
                    <h6 class="text-center h6-login oi">Olá {{ user.username }}</h6>
                {% endif %}
                <a href="{% url 'lista' %}"><button class="btn btn-success btn-block col-md-12 oi">Entrar</button></a>
                <a href="{% url 'logout' %}"><button class="btn btn-danger btn-block col-md-12 oi">Sair</button></a>
            {% else %}
                <h2 class="h2-home">Login</h2>

                <form method="post" action="{% url 'login' %}">
                    {% csrf_token %}
                    <div class="form-group col-md-12 form-input">    
                        <label class="control-label" for="id_nome">CPF</label>
                        <div>
                            <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" class=" form-control" required="" id="id_username">
                        </div>
                    </div> 
           

                    <div class="form-group col-md-12 form-input">    
                        <label class="control-label" for="id_nome">Senha</label>
                        <div>
                            <input type="password" name="password" autocomplete="current-password" class=" form-control" required="" id="id_password">
                        </div>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success btn-block col-md-12">ACESSO</button>
                        <p><a id="a-esqueceu" href="{% url 'esqueci' %}">Esqueceu a senha?</a></p>
                    </div>
                    
                </form>
                
            {% endif %}


        </div>
    </div>
</div>      

<script src="{% static 'js/jquery.min.js' %}"></script>
 
</body>
</html>

acessos/templates/qr_code.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}

{% block title %} Acessar {% endblock %}

{% block main %}

    <div class="branco">
        {% if acessos %}
            <h1>Nome:{{ acessos.nome }}</h1>
            <p>CPF:{{ acessos.cpf }}</p>
        {% else %}
            <h1>Usuário não encontrado.</h1>
        {% endif %}

    <!--Foto-->

            <div id="foto-acesso" class="col-12">
                <img class="col-12 image centered" src="/media/{{ acessos.foto }}" alt=""> 
            </div>

    <!--Qr Code-->
            <div id="qr-acesso" class="col-12">
                <input id="text" type="hidden" value="88800015" style="width:80%" />
                <div id="qrcode" class="col-12">

                </div>
            </div>
    
    </div>

{% endblock %}